# Generated by Django 3.1.5 on 2021-03-29 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2021, verbose_name='year')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=3, verbose_name='month')),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=29, verbose_name='day')),
                ('hour', models.FloatField(default=0, verbose_name='hour')),
                ('comment', models.CharField(blank=True, max_length=250, verbose_name='comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=250, verbose_name='language')),
                ('purpose', models.CharField(choices=[('現在の仕事', '現在の仕事'), ('転職', '転職'), ('趣味', '趣味'), ('その他', 'その他')], default=('その他', 'その他'), max_length=250, verbose_name='purpose')),
                ('weekday_study', models.FloatField(default=0, verbose_name='weekdays')),
                ('holiday_study', models.FloatField(default=0, verbose_name='holidays')),
                ('is_private', models.TextField(blank=True, max_length=250, verbose_name='is_private')),
                ('is_continue', models.CharField(choices=[('1', '使用中'), ('0', '退会希望')], default=('1', '使用中'), max_length=250, verbose_name='is_continue')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
